# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-09 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=2000)),
                ('author', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('className', models.CharField(max_length=20)),
                ('teamNumber', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('file', models.FileField(upload_to='uploadFiles/%Y%m%d')),
                ('teamNumber', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=2000)),
                ('author', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('file', models.FileField(upload_to='uploadFiles/%Y%m%d')),
                ('teamNumber', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=2000)),
                ('author', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('teamNumber', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='coordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=2000)),
                ('author', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('teamNumber', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=2000)),
                ('author', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('teamNumber', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=2000)),
                ('author', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('file', models.FileField(upload_to='uploadFiles/%Y%m%d')),
                ('teamNumber', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='patent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=2000)),
                ('author', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('file', models.FileField(upload_to='uploadFiles/%Y%m%d')),
                ('teamNumber', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='public',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=2000)),
                ('author', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('teamNumber', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='researchClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('describe', models.CharField(max_length=300)),
                ('teamNumber', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='researchTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('teamNumber', models.CharField(max_length=20)),
                ('picture', models.ImageField(upload_to='PictureFiles/%Y%m%d')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=50)),
                ('qqnumber', models.CharField(max_length=50)),
                ('describe', models.CharField(max_length=300)),
                ('classNum', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='researchUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('teamNumber', models.CharField(max_length=20)),
                ('picture', models.ImageField(upload_to='PictureFiles/%Y%m%d')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=50)),
                ('qqnumber', models.CharField(max_length=50)),
                ('describe', models.CharField(max_length=300)),
                ('classNum', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=2000)),
                ('author', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('file', models.FileField(upload_to='uploadFiles/%Y%m%d')),
                ('teamNumber', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('describe', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('status', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=50)),
                ('teamNumber', models.CharField(max_length=20)),
            ],
        ),
    ]
